- name: "mobile_sam_20230629"
  display_name: Segment Anything (MobileSAM)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/mobile_sam_20230629.zip
- name: "sam_vit_b_01ec64"
  display_name: Segment Anything (ViT-B)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_b_01ec64.zip
- name: "sam_vit_b_01ec64_quant"
  display_name: Segment Anything (ViT-B Quant)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_b_01ec64_quant.zip
- name: "sam_vit_l_0b3195"
  display_name: Segment Anything (ViT-L)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_l_0b3195.zip
- name: "sam_vit_l_0b3195_quant"
  display_name: Segment Anything (ViT-L Quant)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_l_0b3195_quant.zip
- name: "sam_vit_h_4b8939"
  display_name: Segment Anything (ViT-H)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939.zip
- name: "sam_vit_h_4b8939_quant"
  display_name: Segment Anything (ViT-H Quant)
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939_quant.zip
- name: "yolov5n-r20230415"
  display_name: YOLOv5n
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5n-r20230415.zip
- name: "yolov5s-r20230415"
  display_name: YOLOv5s
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5s-r20230415.zip
- name: "yolov5m-r20230415"
  display_name: YOLOv5m
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5m-r20230415.zip
- name: "yolov5l-r20230415"
  display_name: YOLOv5l
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5l-r20230415.zip
- name: "yolov5x-r20230415"
  display_name: YOLOv5x
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5x-r20230415.zip
- name: "yolov8n-r20230415"
  display_name: YOLOv8n
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8n-r20230415.zip
- name: "yolov8s-r20230415"
  display_name: YOLOv8s
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8s-r20230415.zip
- name: "yolov8m-r20230415"
  display_name: YOLOv8m
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8m-r20230415.zip
- name: "yolov8l-r20230415"
  display_name: YOLOv8l
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8l-r20230415.zip
- name: "yolov8x-r20230415"
  display_name: YOLOv8x
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8x-r20230415.zip
