- model_name: "segment_anything_vit_b_quant-r20230416"
  config_file: "segment_anything_vit_b_quant.yaml"
- model_name: "segment_anything_vit_b-r20230416"
  config_file: "segment_anything_vit_b.yaml"
- model_name: "segment_anything_vit_l_quant-r20230416"
  config_file: "segment_anything_vit_l_quant.yaml"
- model_name: "segment_anything_vit_l-r20230416"
  config_file: "segment_anything_vit_l.yaml"
- model_name: "segment_anything_vit_h_quant-r20230416"
  config_file: "segment_anything_vit_h_quant.yaml"
- model_name: "yolov5n-r20230415"
  config_file: "yolov5n.yaml"
- model_name: "yolov5s-r20230415"
  config_file: "yolov5s.yaml"
- model_name: "yolov5m-r20230415"
  config_file: "yolov5m.yaml"
- model_name: "yolov5l-r20230415"
  config_file: "yolov5l.yaml"
- model_name: "yolov5x-r20230415"
  config_file: "yolov5x.yaml"
- model_name: "yolov8n-r20230415"
  config_file: "yolov8n.yaml"
- model_name: "yolov8s-r20230415"
  config_file: "yolov8s.yaml"
- model_name: "yolov8m-r20230415"
  config_file: "yolov8m.yaml"
- model_name: "yolov8l-r20230415"
  config_file: "yolov8l.yaml"
- model_name: "yolov8x-r20230415"
  config_file: "yolov8x.yaml"
