- name: "segment_anything_vit_b_quant-r20230416"
  display_name: Segment Anything (ViT-B)
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/segment_anything_vit_b_quant-r20230416.zip
- name: "segment_anything_vit_b-r20230416"
  display_name: Segment Anything (ViT-B Quant)
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/segment_anything_vit_b-r20230416.zip
- name: "segment_anything_vit_l_quant-r20230416"
  display_name: Segment Anything (ViT-L)
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/segment_anything_vit_l-r20230416.zip
- name: "segment_anything_vit_l-r20230416"
  display_name: Segment Anything (ViT-L Quant)
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/segment_anything_vit_l_quant-r20230416.zip
- name: "segment_anything_vit_h-r20230416"
  display_name: Segment Anything (ViT-H)
  download_url: https://huggingface.co/vietanhdev/anylabeling-segment-anything-vit-h/resolve/main/sam_vit_h_4b8939.zip
- name: "segment_anything_vit_h_quant-r20230416"
  display_name: Segment Anything (ViT-H Quant)
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/segment_anything_vit_h_quant-r20230416.zip
- name: "yolov5n-r20230415"
  display_name: YOLOv5n
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5n-r20230415.zip
- name: "yolov5s-r20230415"
  display_name: YOLOv5s
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5s-r20230415.zip
- name: "yolov5m-r20230415"
  display_name: YOLOv5m
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5m-r20230415.zip
- name: "yolov5l-r20230415"
  display_name: YOLOv5l
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5l-r20230415.zip
- name: "yolov5x-r20230415"
  display_name: YOLOv5x
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov5x-r20230415.zip
- name: "yolov8n-r20230415"
  display_name: YOLOv8n
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8n-r20230415.zip
- name: "yolov8s-r20230415"
  display_name: YOLOv8s
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8s-r20230415.zip
- name: "yolov8m-r20230415"
  display_name: YOLOv8m
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8m-r20230415.zip
- name: "yolov8l-r20230415"
  display_name: YOLOv8l
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8l-r20230415.zip
- name: "yolov8x-r20230415"
  display_name: YOLOv8x
  download_url: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.4.0/yolov8x-r20230415.zip
