type: segment_anything
name: segment_anything_vit_b-r20230416
display_name: Segment Anything (ViT-B)
encoder_model_path: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.2.0/segment_anything_vit_b_encoder.onnx
decoder_model_path: https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.2.0/segment_anything_vit_b_decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
